# Generated by Django 4.2 on 2026-08-30 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_alter_proveedor_id'),
        ('productos', '0002_alter_producto_id'),
        ('pedidos', '0002_alter_backorder_id_alter_pedido_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='precio_unitario',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='total',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='proveedores.proveedor'),
        ),
        migrations.CreateModel(
            name='DetallesPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
            options={
                'verbose_name_plural': 'Detalles de Pedidos',
            },
        ),
    ]
