# Generated by Django 4.2 on 2026-09-02 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_imagen_alter_producto_precio'),
        ('pedidos', '0003_remove_pedido_cantidad_remove_pedido_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detallespedido',
            unique_together={('pedido', 'producto')},
        ),
    ]
