# Generated by Django 4.2 on 2026-09-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_detallespedido_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_entrega',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
