# Generated by Django 4.2 on 2026-09-03 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0003_producto_imagen_alter_producto_precio'),
        ('pedidos', '0005_remove_pedido_fecha_entrega_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Almacenes',
            },
        ),
        migrations.AlterModelOptions(
            name='backorder',
            options={'verbose_name_plural': 'Back Orders'},
        ),
        migrations.RenameField(
            model_name='backorder',
            old_name='cantidad_pendiente',
            new_name='cantidad',
        ),
        migrations.AddField(
            model_name='backorder',
            name='entregado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='backorder',
            name='orden_compra',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='backorder',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
        migrations.AddField(
            model_name='detallespedido',
            name='folio_factura',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detallespedido',
            name='pendiente',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detallespedido',
            name='recibido',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='orden_compra',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='orden_venta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_solicitados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='backorder',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backorders', to='pedidos.pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('solicitado', 'Solicitado'), ('entregado', 'Entregado')], default='pendiente', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='detallespedido',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='backorder',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.almacen'),
        ),
        migrations.AddField(
            model_name='detallespedido',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.almacen'),
        ),
        migrations.AlterUniqueTogether(
            name='detallespedido',
            unique_together={('pedido', 'producto', 'almacen')},
        ),
    ]
