# Generated by Django 4.2 on 2026-09-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_almacen_alter_backorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallespedido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
